<testsuite name="login.User Login" tests="8" errors="8" failures="0" skipped="0" time="0.0" timestamp="2025-10-02T23:25:47.707793" hostname="LAPTOP-GPCU1J1Q"><testcase classname="login.User Login" name="Successful login with valid credentials" status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @smoke @login
  Scenario: Successful login with valid credentials
    Given I am on the login page ... error in 0.000s
    When I login with username "testuser" and password "password123" ... skipped in 0.000s
    Then I should be redirected to the home page ... skipped in 0.000s
    And I should see the welcome message ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with invalid credentials" status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @negative @login
  Scenario: Login with invalid credentials
    Given I am on the login page ... error in 0.000s
    When I login with username "invalid" and password "wrongpass" ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s
    And the error message should contain "invalid credentials" ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with empty username" status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @negative @login
  Scenario: Login with empty username
    Given I am on the login page ... error in 0.000s
    When I enter username "" ... undefined in 0.000s
    And I enter password "password123" ... skipped in 0.000s
    And I click the login button ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s
    And the error message should contain "username" ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with empty password" status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @negative @login
  Scenario: Login with empty password
    Given I am on the login page ... error in 0.000s
    When I enter username "testuser" ... skipped in 0.000s
    And I enter password "" ... undefined in 0.000s
    And I click the login button ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s
    And the error message should contain "password" ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with different invalid credentials -- @1.1 " status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @login
  Scenario Outline: Login with different invalid credentials -- @1.1 
    Given I am on the login page ... error in 0.000s
    When I login with username "invalid" and password "pass123" ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with different invalid credentials -- @1.2 " status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @login
  Scenario Outline: Login with different invalid credentials -- @1.2 
    Given I am on the login page ... error in 0.000s
    When I login with username "user123" and password "wrongpass" ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with different invalid credentials -- @1.3 " status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @login
  Scenario Outline: Login with different invalid credentials -- @1.3 
    Given I am on the login page ... error in 0.000s
    When I login with username "testuser" and password "wrongpass" ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="login.User Login" name="Login with different invalid credentials -- @1.4 " status="error" time="0.0"><error type="AttributeError" message="'Context' object has no attribute 'driver'">
<![CDATA[
Failing step: Given I am on the login page ... error in 0.000s
Location: features/login.feature:7
Traceback (most recent call last):
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\model.py", line 1991, in run
    match.run(runner.context)
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\matchers.py", line 105, in run
    self.func(context, *args, **kwargs)
  File "features\steps\login_steps.py", line 7, in step_navigate_to_login
    context.login_page = LoginPage(context.driver)
                                   ^^^^^^^^^^^^^^
  File "C:\Users\Manish\AppData\Local\Programs\Python\Python312\Lib\site-packages\behave\runner.py", line 430, in __getattr__
    raise AttributeError(msg)
AttributeError: 'Context' object has no attribute 'driver'
]]>
</error><system-out>
<![CDATA[
@scenario.begin

  @login
  Scenario Outline: Login with different invalid credentials -- @1.4 
    Given I am on the login page ... error in 0.000s
    When I login with username "wronguser" and password "password123" ... skipped in 0.000s
    Then I should see the error message ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>